name: automate issue status

on:
    pull_request:
        types: [opened, closed]
    issues:
        types: [assigned]

jobs:
    update-issue-status:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: update issue status when PR is opened
              if: github.event_name == 'pull_request' && github.event.action == 'opened'
              uses: actions/github-script@v6
              with:
                  script: |
                      const issueNumber = context.payload.pull_request.number;
                      await github.rest.issues.update({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issueNumber,
                        labels: ['status: validate']
                      });

            - name: update issue status when PR is closed
              if: github.event_name == 'pull_request' && github.event.action == 'closed'
              uses: actions/github-script@v6
              with:
                  script: |
                      const issueNumber = context.payload.pull_request.number;
                      await github.rest.issues.update({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issueNumber,
                        labels: ['status: done']
                      });

            - name: update issue status when assigned
              if: github.event_name == 'issues' && github.event.action == 'assigned'
              uses: actions/github-script@v6
              with:
                  script: |
                      const issueNumber = context.payload.issue.number;
                      const assignee = context.payload.assignee.login;

                      // Update the issue status to "in progress" when assigned
                      await github.rest.issues.update({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issueNumber,
                        labels: ['status: in progress'] // Set status to "in progress"
                      });
