name: automate issue status

on:
    pull_request:
        types: [opened, closed]
    issues:
        types: [assigned]

permissions:
    issues: write
    pull-requests: write
    repository-projects: write

jobs:
    update-issue-status:
        name: move issues to repository project column
        runs-on: ubuntu-latest
        # another day, we shall make this possible ... seems like project
        # cards have been deprecated and can't mutate through github api x_x
